backend:
  name: git-gateway
  repo: Code-For-Chicago/code-for-chicago-jekyll
  branch: main
publish_mode: editorial_workflow
media_folder: "images/uploads"
collections:
  - name: "portfolio" # Used in routes, e.g., /admin/collections/blog
    label: "Portfolio Page" # Used in the UI
    folder: "_posts/portfolio" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md

    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "portfolio",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tag", name: "areas", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Featured Image Text", name: "imgtext", widget: "string" }
      - { label: "Featured Image Alt", name: "alt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Coming Soon",
          name: "is_preview",
          widget: "boolean",
          default: false,
        }
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects Page" # Used in the UI
    folder: "_posts/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "project",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tag", name: "areas", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Thumbnail Description", name: "imgtext", widget: "string" }
      - { label: "Featured Image Alt", name: "alt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
